In [ ]:
import pandas as pd

In [5]:
heart_disease_dataset = pd.read_csv("https://raw.githubusercontent.com/mcchucho/mlheartdisease/main/heart_failure_clinical_records_dataset.csv", sep=",")
heart_disease_dataset.head()

    age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0  75.0        0                       582  ...        0     4            1
1  55.0        0                      7861  ...        0     6            1
2  65.0        0                       146  ...        1     7            1
3  50.0        1                       111  ...        0     7            1
4  65.0        1                       160  ...        0     8            1

[5 rows x 13 columns]